### PR TITLE
Fix Trips Page Timezone Issue

### LINKED ISSUE #89: Fix Timezones Issue for Trip Dates
### Issue summary

The current user's timezone dictates the timezone of the Firestore Timestamp object that is stored for the start and end dates of a trip. This can cause dates to be off by one if the timezone used to create/edit the trip is different than the current user timezone. 

### Expected behavior

Ensure the date displayed on the view trips page (including the SaveTripModal) is correct regardless of the user's current timezone.

### Actual behavior

All JS Dates and Firestore Timestamps are made in the current users local timezone.

### PR DESCRIPTION
**Pull request by zghera**
### What is a quick description of the change?

Fix #89 by ensuring that all JS Date objects use UTC. 

This ensures that no matter where the user is located when updating or viewing the trips, the start and end date of the trips will remain the same from the last update.

### Is this fixing an issue?

Fixes #89: see above.

### Are there more details that are relevant?

Moves getDateRangeString into `time.js`.

### Check lists (check `x` in `[ ]` of list items)

- [x] Test written/updating
- [x] Tests passing
- [x] Coding style (indentation, etc)

### CODE REVIEW

File: frontend/src/components/Utils/time.js [hunk 1]
```diff
@@ -51,17 +51,48 @@ export function timestampToFormatted(msTimestamp, timezone = 'America/New_York')
...
+
+/**
+ * Returns the string date range of the trip associated with the Trip document
+ * start and end date timestamps.
+ *
+ * Notes:
+ * - The date strings are created in the UTC timezone in order to avoid issues
+ * where a user's timezone at last update of the trip is different than the
+ * user's current timezone when viewing a trip.
+ * - The months retreived from `getUTCMonth` are 0 indexed rather than 1 indexed
```
Comment (keiffer01) [inline frontend/src/components/Utils/time.js:81]: Nit:
```suggestion
 * - The months retrieved from `getUTCMonth` are 0 indexed rather than 1 indexed
```

Comment (zghera) [reply frontend/src/components/Utils/time.js]: Fixed.
