### PR TITLE
Modify website flows for authentication

### LINKED ISSUE #59: Modify Authentication Flows
### Issue summary

See differences between expected and actual behavior.

### Expected behavior

- When the user is already authenticated, they should be automatically redirected to the VIEW_TRIPS page if they go to the SIGN_IN page.
- When the user clicks the Sign Out button, they should be redirected to the LANDING page.

### Actual behavior

- An already authenticated user that navigates to the SIGN_IN page will not be automatically redirected to their trips page.
- When the user clicks the Sign Out button, they are redirected to the SIGN_IN page instead of the LANDING page.

### Steps to reproduce (including any preconditions)

As described in the expected behavior section.

### PR DESCRIPTION
**Pull request by keiffer01**
### What is a quick description of the change?

Modify some of the authentication flows to be as described in #59.

### Is this fixing an issue?

Fixes #59.

### Are there more details that are relevant?

none

### Check lists (check `x` in `[ ]` of list items)

- [  ] Test written/updating
- [  ] Tests passing
- [x] Coding style (indentation, etc)

No tests written as the Redirect external component was used and redirecting with useHistory had been tested before. (If you think tests _should_ be added though I can try to add some)

### CODE REVIEW

File: frontend/src/components/SignIn/index.js [hunk 1]
```diff
@@ -1,10 +1,12 @@
 import React from 'react';
+import { Redirect } from 'react-router-dom';
+import { AuthContext } from '../Auth';
 
 import * as firebase from 'firebase/app';
 import app from '../Firebase';
 import StyledFirebaseAuth from 'react-firebaseui/StyledFirebaseAuth';
 
-import {VIEW_TRIPS} from '../../constants/routes';
+import { VIEW_TRIPS } from '../../constants/routes';
```
Comment (ananyeet) [inline frontend/src/components/SignIn/index.js:9]: routes.js?

Comment (keiffer01) [reply frontend/src/components/SignIn/index.js:9]: Oops yeah, fixed.

File: frontend/src/components/Header/UserInfo.js [hunk 2]
```diff
@@ -1,9 +1,12 @@
-import React from 'react';
+import React  from 'react';
```
Comment (Hiram-Silvey) [inline frontend/src/components/Header/UserInfo.js:1]: Remove extra space between "React" and "from."

File: frontend/src/components/Header/UserInfo.js [hunk 3]
```diff
@@ -1,9 +1,12 @@
...
+import { useHistory } from 'react-router-dom';
 import authUtils from '../AuthUtils';
 
 import '../../styles/header.css';
 import Button from 'react-bootstrap/Button';
 
+import { LANDING } from '../../constants/routes.js';
+
```
Comment (Hiram-Silvey) [inline frontend/src/components/Header/UserInfo.js:9]: What's the specific style used for these imports?

File: frontend/src/components/Header/UserInfo.js [hunk 4]
```diff
@@ -13,29 +16,37 @@ const BOOTSTRAP_SPACING_CLASS =
...
+  const history = useHistory();
+
+  /**
+   * Redirects the user to the LANDING page first before actually signing them
+   * out.
+   */
+  function signOutAndRedirectToLanding() {
+    history.push(LANDING);
+    authUtils.signOut();
   }
```
Comment (Hiram-Silvey) [inline frontend/src/components/Header/UserInfo.js:29]: Why does this redirect to the landing page? Also, why is the order redirect -> log out?

File: frontend/src/components/Header/UserInfo.js (hunk 2 above)
Comment (keiffer01) [reply frontend/src/components/Header/UserInfo.js:1]: Fixed.

File: frontend/src/components/Header/UserInfo.js (hunk 3 above)
Comment (keiffer01) [reply frontend/src/components/Header/UserInfo.js:9]: As described in #76, I think we've settled on:
```
React stuff

Firestore, Bootstrap, other libraries

Local imports
```
I've updated the spacing to reflect this.

File: frontend/src/components/Header/UserInfo.js (hunk 4 above)
Comment (keiffer01) [reply frontend/src/components/Header/UserInfo.js:29]: Right now, the way authentication works is that whenever the website notices that the user is not logged in, it'll immediately redirect them to the signin page. This is so if a user tries to access a private page like View Trips but they aren't logged in, they can quickly sign in once they are redirected to the sign in page.

I'm assuming most users would expect to be redirected to the landing/home page when they press the "Sign Out" button instead of being redirected to the signin page. So I first tell the browser to bring the user to the home page before logging them out. If I did it the other way around, the user would first be brought to the sign in page, then brought to the home page immediately after, which might look strange if there are any delays.
