### PR TITLE
Fix Data Loading issue

### LINKED ISSUE #140: Fix MomentJS data loading.
### Issue summary

MomentJS TZ returns a "data not loaded" error when using the library. As a result, it uses and displays GMT time. 

### Expected behavior

Data should be loaded appropriately, and as a result all dates should be consistent. 

### Actual behavior

Data is, apparently, not loaded correctly. So the "edit activity" page is mismatched from the header for that activity. 

### Your environment

Include version numbers

- Browser: Chrome
- Moment Timezone version: 0.5.31
- npm version: 6.14.7

### Additional Information

The [momentJS documentation](https://momentjs.com/timezone/docs/#/use-it/node-js/) states that the data is automatically loaded.

### PR DESCRIPTION
**Pull request by ananyeet**
### What is a quick description of the change?

This PR fixes #140. The functions which were throwing the error were unable to recognize time zones with spaces in their names instead of underscores (i.e. "America/New York" vs "America/New_York", replacement done for visual purposes). The solution is to replace the spaces with underscores.

### Are there more details that are relevant?

no

### Check lists (check `x` in `[ ]` of list items)

- [x] Test written/updating
- [x] Tests passing
- [x] Coding style (indentation, etc)

Please explain why any are not present, if any.

### CODE REVIEW

File: frontend/src/components/Utils/time.js [hunk 1]
```diff
@@ -40,10 +44,12 @@ export function timestampToDateFormatted(msTimestamp, timezone='America/New_York
  * @param {string} timezone Timezone in which to convert.
  * @returns {string} Formatted time.
  */
-export function timestampToFormatted(msTimestamp, timezone = 'America/New_York') {
+export function timestampToFormatted(msTimestamp, timezone = '') {
```
Comment (zghera) [inline frontend/src/components/Utils/time.js:47]: Do you need to add the default value to the JSDoc for `timezone` param?

Comment (ananyeet) [reply frontend/src/components/Utils/time.js:47]: oooh yeah I forgot about that! Thanks!

**Comment by ananyeet** [comment]
Received @Hiram-Silvey 's verbal approval to merge since this is the last day of the internship and he was not able to review the PR.
