### PR TITLE
Change Activity Sorting Function

### LINKED ISSUE #125: Activity proper event sorting and ordering.
### Issue summary

The activities do not display in the correct order. 

### Expected behavior

When a list of activities is displayed, the activities should be in chronological order, and the days should be in chronological order.

### Actual behavior

Sometimes activities aren't displayed in chronological order. They appear to be displayed in some other order (not in order of entry into the database, either).

### Steps to reproduce (including any preconditions)

Add activities in non-chronological order to the trip. 

### Screenshot/screencast of this problem (if possible)

The May activities are coming after the June activities. 

image
image

### PR DESCRIPTION
**Pull request by ananyeet**
### What is a quick description of the change?

Change activity sorting function so days are listed in order. 

### Is this fixing an issue?

Fixes #125

### Are there more details that are relevant?
none

### Check lists (check `x` in `[ ]` of list items)

- [x] Test written/updating
- [x] Tests passing
- [x] Coding style (indentation, etc)

Please explain why any are not present, if any.

### Any additional comments?

{Fill in here or remove (leave question)}

### CODE REVIEW

File: frontend/src/components/ViewActivities/activityfns.js [hunk 1]
```diff
@@ -62,8 +63,12 @@ export function sortByDate(tripActivities) {
...
     }
   }
-  // Sort activities by date.
-  let activitiesSorted = Array.from(activities).sort(compareActivities);
+  // Sort activities by date.  
+  let activitiesSorted = Array.from(activities).sort((a, b) => {
+    const aDate = moment.utc(a[0], "YYYY-MM-DD").valueOf();
+    const bDate = moment.utc(b[0], "YYYY-MM-DD").valueOf();
+    return aDate < bDate ? -1 : 1;
+  });
```
Comment (zghera) [inline frontend/src/components/ViewActivities/activityfns.js:71]: Isn't this change already made in #122 ? If so remove it in one or the other PR.

Comment (ananyeet) [reply frontend/src/components/ViewActivities/activityfns.js:71]: closed #122

**Comment by ananyeet** [comment]
Received @Hiram-Silvey 's verbal approval to merge since this is the last day of the internship and he was not able to review the PR.
